// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using app.db.Context;

#nullable disable

namespace application.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20241217191538_nupdate5")]
    partial class nupdate5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<int>("cart_seq");

            modelBuilder.HasSequence<int>("color_seq");

            modelBuilder.HasSequence<int>("headphones_image_seq");

            modelBuilder.HasSequence<int>("laptop_image_seq");

            modelBuilder.HasSequence<int>("orders_seq");

            modelBuilder.HasSequence<int>("os_brand_seq");

            modelBuilder.HasSequence<int>("os_seq");

            modelBuilder.HasSequence<int>("phone_image_seq");

            modelBuilder.HasSequence<int>("processor_brand_seq");

            modelBuilder.HasSequence<int>("processor_model_seq");

            modelBuilder.HasSequence<int>("producer_seq");

            modelBuilder.HasSequence<int>("product_seq");

            modelBuilder.HasSequence<int>("smartwatch_image_seq");

            modelBuilder.HasSequence<int>("user_seq");

            modelBuilder.HasSequence<int>("videocard_brand_seq");

            modelBuilder.HasSequence<int>("videocard_model_seq");

            modelBuilder.Entity("app.db.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("next value for cart_seq");

                    b.Property<int?>("HeadphonesId")
                        .HasColumnType("int");

                    b.Property<int?>("LaptopId")
                        .HasColumnType("int");

                    b.Property<int?>("PhonesId")
                        .HasColumnType("int");

                    b.Property<int?>("SmartWatchesId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HeadphonesId");

                    b.HasIndex("LaptopId");

                    b.HasIndex("PhonesId");

                    b.HasIndex("SmartWatchesId");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("app.db.Entities.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("next value for color_seq");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Color");
                });

            modelBuilder.Entity("app.db.Entities.Headphones.Headphones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("next value for product_seq");

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("OrdersId")
                        .HasColumnType("int");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("ProducerId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<float>("Wheight")
                        .HasColumnType("real");

                    b.Property<bool>("Wireless")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("OrdersId");

                    b.HasIndex("ProducerId");

                    b.ToTable("Headphones");
                });

            modelBuilder.Entity("app.db.Entities.Headphones.HeadphonesImages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("next value for headphones_image_seq");

                    b.Property<int>("HeadphonesId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Img")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("HeadphonesId");

                    b.ToTable("HeadphonesImages");
                });

            modelBuilder.Entity("app.db.Entities.Laptop.Laptop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("next value for product_seq");

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OSId")
                        .HasColumnType("int");

                    b.Property<int?>("OrdersId")
                        .HasColumnType("int");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("ProcessorId")
                        .HasColumnType("int");

                    b.Property<int>("ProducerId")
                        .HasColumnType("int");

                    b.Property<int>("RAMMemorySize")
                        .HasColumnType("int");

                    b.Property<int>("SSDMemorySize")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("VideoCardModelId")
                        .HasColumnType("int");

                    b.Property<float>("Wheight")
                        .HasColumnType("real");

                    b.Property<float>("Width")
                        .HasMaxLength(20)
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("OSId");

                    b.HasIndex("OrdersId");

                    b.HasIndex("ProcessorId");

                    b.HasIndex("ProducerId");

                    b.HasIndex("VideoCardModelId");

                    b.ToTable("Laptop");
                });

            modelBuilder.Entity("app.db.Entities.Laptop.LaptopImages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("next value for laptop_image_seq");

                    b.Property<byte[]>("Img")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("LaptopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LaptopId");

                    b.ToTable("LaptopImages");
                });

            modelBuilder.Entity("app.db.Entities.Laptop.VideoCard.VideoCardBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("next value for videocard_brand_seq");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("VideoCardBrand");
                });

            modelBuilder.Entity("app.db.Entities.Laptop.VideoCard.VideoCardModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("next value for videocard_model_seq");

                    b.Property<float>("BaseFrequency")
                        .HasColumnType("real");

                    b.Property<float>("BoostFrequency")
                        .HasColumnType("real");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("VideoCardModel");
                });

            modelBuilder.Entity("app.db.Entities.OS.OS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("next value for os_seq");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("OS");
                });

            modelBuilder.Entity("app.db.Entities.OS.OSBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("next value for os_brand_seq");

                    b.Property<bool>("IsLaptop")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("OSBrand");
                });

            modelBuilder.Entity("app.db.Entities.Orders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("next value for orders_seq");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("app.db.Entities.Phone.Phone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("next value for product_seq");

                    b.Property<int>("Battery")
                        .HasColumnType("int");

                    b.Property<int>("Camera")
                        .HasColumnType("int");

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<int>("InternalMemorySize")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OSId")
                        .HasColumnType("int");

                    b.Property<int?>("OrdersId")
                        .HasColumnType("int");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("ProcessorId")
                        .HasColumnType("int");

                    b.Property<int>("ProducerId")
                        .HasColumnType("int");

                    b.Property<int>("RAM")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<bool>("WaterProtection")
                        .HasColumnType("bit");

                    b.Property<float>("Wheight")
                        .HasColumnType("real");

                    b.Property<float>("Width")
                        .HasMaxLength(30)
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("OSId");

                    b.HasIndex("OrdersId");

                    b.HasIndex("ProcessorId");

                    b.HasIndex("ProducerId");

                    b.ToTable("Phone");
                });

            modelBuilder.Entity("app.db.Entities.Phone.PhoneImages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("next value for phone_image_seq");

                    b.Property<byte[]>("Img")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("PhoneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PhoneId");

                    b.ToTable("PhoneImages");
                });

            modelBuilder.Entity("app.db.Entities.Processor.ProcessorBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("next value for processor_brand_seq");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ProcessorBrand");
                });

            modelBuilder.Entity("app.db.Entities.Processor.ProcessorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("next value for processor_model_seq");

                    b.Property<float>("BaseFrequency")
                        .HasColumnType("real");

                    b.Property<float>("BoostFrequency")
                        .HasColumnType("real");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<bool>("IsLaptop")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("ProcessorModel");
                });

            modelBuilder.Entity("app.db.Entities.Producer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("next value for producer_seq");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Producer");
                });

            modelBuilder.Entity("app.db.Entities.Reviews", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("HeadphonesId")
                        .HasColumnType("int");

                    b.Property<int?>("LaptopId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("PhonesId")
                        .HasColumnType("int");

                    b.Property<int?>("SmartWatchesId")
                        .HasColumnType("int");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HeadphonesId");

                    b.HasIndex("LaptopId");

                    b.HasIndex("PhonesId");

                    b.HasIndex("SmartWatchesId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("app.db.Entities.SmartWatches.SmartWatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("next value for product_seq");

                    b.Property<bool>("Bleatouth")
                        .HasColumnType("bit");

                    b.Property<bool>("Calls")
                        .HasColumnType("bit");

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<bool>("Gps")
                        .HasColumnType("bit");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OSId")
                        .HasColumnType("int");

                    b.Property<int?>("OrdersId")
                        .HasColumnType("int");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("ProducerId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<float>("Wheight")
                        .HasColumnType("real");

                    b.Property<float>("Width")
                        .HasMaxLength(20)
                        .HasColumnType("real");

                    b.Property<bool>("Wifi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("OSId");

                    b.HasIndex("OrdersId");

                    b.HasIndex("ProducerId");

                    b.ToTable("SmartWatches");
                });

            modelBuilder.Entity("app.db.Entities.SmartWatches.SmartWatchImages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("next value for smartwatch_image_seq");

                    b.Property<byte[]>("Img")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("SmartWatchesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SmartWatchesId");

                    b.ToTable("SmartWatchesImages");
                });

            modelBuilder.Entity("app.db.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("next value for user_seq");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("UserImage")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("app.db.Entities.Cart", b =>
                {
                    b.HasOne("app.db.Entities.Headphones.Headphones", "Headphones")
                        .WithMany("Cart")
                        .HasForeignKey("HeadphonesId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("app.db.Entities.Laptop.Laptop", "Laptop")
                        .WithMany("Cart")
                        .HasForeignKey("LaptopId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("app.db.Entities.Phone.Phone", "Phone")
                        .WithMany("Cart")
                        .HasForeignKey("PhonesId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("app.db.Entities.SmartWatches.SmartWatch", "SmartWatch")
                        .WithMany("Cart")
                        .HasForeignKey("SmartWatchesId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("app.db.Entities.User", "User")
                        .WithMany("Cart")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Headphones");

                    b.Navigation("Laptop");

                    b.Navigation("Phone");

                    b.Navigation("SmartWatch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("app.db.Entities.Headphones.Headphones", b =>
                {
                    b.HasOne("app.db.Entities.Color", "Color")
                        .WithMany("Headphones")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("app.db.Entities.Orders", null)
                        .WithMany("Headphones")
                        .HasForeignKey("OrdersId");

                    b.HasOne("app.db.Entities.Producer", "Producer")
                        .WithMany("Headphones")
                        .HasForeignKey("ProducerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("Producer");
                });

            modelBuilder.Entity("app.db.Entities.Headphones.HeadphonesImages", b =>
                {
                    b.HasOne("app.db.Entities.Headphones.Headphones", "Headphones")
                        .WithMany("ProductImages")
                        .HasForeignKey("HeadphonesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Headphones");
                });

            modelBuilder.Entity("app.db.Entities.Laptop.Laptop", b =>
                {
                    b.HasOne("app.db.Entities.Color", "Color")
                        .WithMany("Laptops")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("app.db.Entities.OS.OS", "OS")
                        .WithMany("Laptops")
                        .HasForeignKey("OSId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("app.db.Entities.Orders", null)
                        .WithMany("Laptops")
                        .HasForeignKey("OrdersId");

                    b.HasOne("app.db.Entities.Processor.ProcessorModel", "Processor")
                        .WithMany("Laptops")
                        .HasForeignKey("ProcessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("app.db.Entities.Producer", "Producer")
                        .WithMany("Laptops")
                        .HasForeignKey("ProducerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("app.db.Entities.Laptop.VideoCard.VideoCardModel", "VideoCardModel")
                        .WithMany("Laptops")
                        .HasForeignKey("VideoCardModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("OS");

                    b.Navigation("Processor");

                    b.Navigation("Producer");

                    b.Navigation("VideoCardModel");
                });

            modelBuilder.Entity("app.db.Entities.Laptop.LaptopImages", b =>
                {
                    b.HasOne("app.db.Entities.Laptop.Laptop", "Laptop")
                        .WithMany("ProductImages")
                        .HasForeignKey("LaptopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Laptop");
                });

            modelBuilder.Entity("app.db.Entities.Laptop.VideoCard.VideoCardModel", b =>
                {
                    b.HasOne("app.db.Entities.Laptop.VideoCard.VideoCardBrand", "Brand")
                        .WithMany("VideoCardModels")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("app.db.Entities.OS.OS", b =>
                {
                    b.HasOne("app.db.Entities.OS.OSBrand", "Brand")
                        .WithMany("OS")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("app.db.Entities.Orders", b =>
                {
                    b.HasOne("app.db.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("app.db.Entities.Phone.Phone", b =>
                {
                    b.HasOne("app.db.Entities.Color", "Color")
                        .WithMany("Phones")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("app.db.Entities.OS.OS", "OS")
                        .WithMany("Phones")
                        .HasForeignKey("OSId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("app.db.Entities.Orders", null)
                        .WithMany("Phones")
                        .HasForeignKey("OrdersId");

                    b.HasOne("app.db.Entities.Processor.ProcessorModel", "Processor")
                        .WithMany("Phones")
                        .HasForeignKey("ProcessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("app.db.Entities.Producer", "Producer")
                        .WithMany("Phones")
                        .HasForeignKey("ProducerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("OS");

                    b.Navigation("Processor");

                    b.Navigation("Producer");
                });

            modelBuilder.Entity("app.db.Entities.Phone.PhoneImages", b =>
                {
                    b.HasOne("app.db.Entities.Phone.Phone", "Phone")
                        .WithMany("ProductImages")
                        .HasForeignKey("PhoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phone");
                });

            modelBuilder.Entity("app.db.Entities.Processor.ProcessorModel", b =>
                {
                    b.HasOne("app.db.Entities.Processor.ProcessorBrand", "Brand")
                        .WithMany("ProcessorModels")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("app.db.Entities.Reviews", b =>
                {
                    b.HasOne("app.db.Entities.Headphones.Headphones", "Headphones")
                        .WithMany("Reviews")
                        .HasForeignKey("HeadphonesId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("app.db.Entities.Laptop.Laptop", "Laptop")
                        .WithMany("Reviews")
                        .HasForeignKey("LaptopId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("app.db.Entities.Phone.Phone", "Phone")
                        .WithMany("Reviews")
                        .HasForeignKey("PhonesId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("app.db.Entities.SmartWatches.SmartWatch", "SmartWatch")
                        .WithMany("Reviews")
                        .HasForeignKey("SmartWatchesId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("app.db.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Headphones");

                    b.Navigation("Laptop");

                    b.Navigation("Phone");

                    b.Navigation("SmartWatch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("app.db.Entities.SmartWatches.SmartWatch", b =>
                {
                    b.HasOne("app.db.Entities.Color", "Color")
                        .WithMany("SmartWatches")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("app.db.Entities.OS.OS", "OS")
                        .WithMany("SmartWatches")
                        .HasForeignKey("OSId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("app.db.Entities.Orders", null)
                        .WithMany("SmartWacthes")
                        .HasForeignKey("OrdersId");

                    b.HasOne("app.db.Entities.Producer", "Producer")
                        .WithMany("SmartWatches")
                        .HasForeignKey("ProducerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("OS");

                    b.Navigation("Producer");
                });

            modelBuilder.Entity("app.db.Entities.SmartWatches.SmartWatchImages", b =>
                {
                    b.HasOne("app.db.Entities.SmartWatches.SmartWatch", "SmartWatch")
                        .WithMany("ProductImages")
                        .HasForeignKey("SmartWatchesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SmartWatch");
                });

            modelBuilder.Entity("app.db.Entities.Color", b =>
                {
                    b.Navigation("Headphones");

                    b.Navigation("Laptops");

                    b.Navigation("Phones");

                    b.Navigation("SmartWatches");
                });

            modelBuilder.Entity("app.db.Entities.Headphones.Headphones", b =>
                {
                    b.Navigation("Cart");

                    b.Navigation("ProductImages");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("app.db.Entities.Laptop.Laptop", b =>
                {
                    b.Navigation("Cart");

                    b.Navigation("ProductImages");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("app.db.Entities.Laptop.VideoCard.VideoCardBrand", b =>
                {
                    b.Navigation("VideoCardModels");
                });

            modelBuilder.Entity("app.db.Entities.Laptop.VideoCard.VideoCardModel", b =>
                {
                    b.Navigation("Laptops");
                });

            modelBuilder.Entity("app.db.Entities.OS.OS", b =>
                {
                    b.Navigation("Laptops");

                    b.Navigation("Phones");

                    b.Navigation("SmartWatches");
                });

            modelBuilder.Entity("app.db.Entities.OS.OSBrand", b =>
                {
                    b.Navigation("OS");
                });

            modelBuilder.Entity("app.db.Entities.Orders", b =>
                {
                    b.Navigation("Headphones");

                    b.Navigation("Laptops");

                    b.Navigation("Phones");

                    b.Navigation("SmartWacthes");
                });

            modelBuilder.Entity("app.db.Entities.Phone.Phone", b =>
                {
                    b.Navigation("Cart");

                    b.Navigation("ProductImages");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("app.db.Entities.Processor.ProcessorBrand", b =>
                {
                    b.Navigation("ProcessorModels");
                });

            modelBuilder.Entity("app.db.Entities.Processor.ProcessorModel", b =>
                {
                    b.Navigation("Laptops");

                    b.Navigation("Phones");
                });

            modelBuilder.Entity("app.db.Entities.Producer", b =>
                {
                    b.Navigation("Headphones");

                    b.Navigation("Laptops");

                    b.Navigation("Phones");

                    b.Navigation("SmartWatches");
                });

            modelBuilder.Entity("app.db.Entities.SmartWatches.SmartWatch", b =>
                {
                    b.Navigation("Cart");

                    b.Navigation("ProductImages");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("app.db.Entities.User", b =>
                {
                    b.Navigation("Cart");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
